config/routes.rb
Rails.application.routes.draw do
  
   get 'home/about' => "homes#about"
  root to:'homes#index'
  
  
  devise_for :users

  resources :homes
  
  resources :users do
    resource :relationships,only:[:create, :destroy]
    # フォローしている人を表示するためのルーティング
    get :followings
    # フォワ−　されている人を表示するためにルーティング
    get :followers
  end
  
    resources :books do 
      resource :likes,only:[:create, :destroy]
      resources :comments,only:[:create,:destroy]
      resource :selects,only:[:create, :destroy]
    end
    
    get '/search' => 'searchs#search'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  

end

app/models/book.rb
class Book < ApplicationRecord
 belongs_to :user 
 has_many :relationships, dependent: :destroy
 has_many :likes, dependent: :destroy
 has_many :comments,dependent: :destroy
 has_many :selects, dependent: :destroy

validates :title, presence: true
validates :body, presence: true, length: { maximum: 200 }


 def likes_by?(user)
  likes.where(user_id: user.id).exists?
 end
 
 def selects_by?(user)
  selects.where(user_id: user.id).exists?
 end
 


end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :book 
  belongs_to :user
  
end

app/models/like.rb
class Like < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
belongs_to :follower, class_name: "User"
belongs_to :following, class_name: "User"

end

app/models/select.rb
class Select < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
 has_many :books,dependent: :destroy
 has_many :likes,dependent: :destroy
 has_many :comments,dependent: :destroy
 has_many :selects, dependent: :destroy
  attachment :profile_image
  
  
  # ----フォロー機能アソシエーション---
  
  #フォローする側のアソシエーション
  has_many :relationships,foreign_key: :following_id
  #フォローする側がフォローしている人の情報取る
  has_many :followings, through: :relationships, source: :follower
  
  
  # フォローされる側のアソシエーション
  has_many :reverse_of_relationships,class_name: 'Relationship',foreign_key: :follower_id
 #フォローされている側がフォローしている情報を取る
  has_many :followers, through: :reverse_of_relationships, source: :following
  

#フォローしているかを確認する
def is_followed_by?(user)
 reverse_of_relationships.find_by(following_id: user.id).present?
end

  validates :name,
    presence: true, uniqueness: true, length: { in: 2..20 }
    # 文字数の制限を設ける→length #長さの範囲を2-20文字→in ..
    # 一意性を保つバリデーション（uniqueness: true）
  validates :introduction,
    length: { maximum: 50 }
    # 長さの下限を50文字に設定→minimum
    # presence: trueは、空欄でないことを確認している


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
#   before_action :current_user, only:[:edit]

def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
        flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book)
    else
    @user = current_user
    @books = Book.all
    render :index
    end 
end

def show
  @new_book = Book.new
  @book = Book.find(params[:id])
  @user = @book.user
  @books = Book.all
  @comment =Comment.new
  @comments = @book.comments
  
end

def index
    @books = Book.all
    @book = Book.new
    @user = current_user
    @users = User.all
end


# ーーー登録ユーザーのみ表示ーーー
  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book)
      flash[:notice] = "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

# ーーー（end)登録ユーザーのみ表示ーーー


private
  def book_params
    params.require(:book).permit(:title,:body,:profile_image)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @book = Book.find(params[:book_id])
    @comment = Comment.new(comment_params)
    @comments = @book.comments
    @comment.user_id = current_user.id
    @comment.book_id = @book.id
    @comment.save
    
    # redirect_to book_path(book)
  end
  
  def destroy
  @book = Book.find(params[:book_id])
  @comment = Comment.find(params[:id])
  @comments = @book.comments
  @comment.destroy
  # redirect_to books_path(comment)
  end
  
  private
  def comment_params
  params.require(:comment).permit(:content)
  end  
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

app/controllers/likes_controller.rb
class LikesController < ApplicationController

   def create
    @book = Book.find(params[:book_id])
    favorite = current_user.likes.new(book_id: @book.id)
    favorite.save
 
   end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = Like.find_by(user_id: current_user.id, book_id: @book.id)
    favorite.destroy
  end
  
  
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController

  def search
    @model = params["search"]["model"] 
    #選択したmodelを@modelに代入
    @value = params["search"]["value"]
    #検索にかけた文字列@valueに代入
    @how = params["search"]["how"]
    #選択した検索方法howを@howに代入
    @datas = search_for(@how, @model, @value)
    #search_forの引数にインスタンス変数を定義
    #最後は@datas に結果が入る
  end
  
  private
  def match(model, value) 
    #search_forでhowがmatchだった場合の処理
    if model == 'user'
      User.where(name: value)
    elsif model == 'book'
      Book.where(title: value)
    end
  end

  def forward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "#{value}%")
    end
  end

  def backward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}")
    end
  end

  def partical(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}%")
    end
  end

  def search_for(how, model, value) #検索方法ごとの条件 
    case how
    when 'match'
      match(model, value)
    when 'forward'
      forward(model, value)
    when 'backward'
      backward(model, value)
    when 'partical'
      partical(model, value)
    end
  end
end

app/controllers/selects_controller.rb
class SelectsController < ApplicationController
  
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.selects.new(book_id: @book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
   end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = Select.find_by(user_id: current_user.id, book_id: @book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end
  
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!
  before_action :current_user, only:[:edit,:update]
    
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
    @not_current_user = User.where.not(id: @user.id)
  end
    
  def show
    @user = User.find(params[:id])
    @user_books = @user.books
    @book = Book.new
    @books = Book.all
  end
    
  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end
    
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path
    else
      render :edit
    end 
  end
  
  
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end
  
  def followers
     user = User.find(params[:user_id])
     @users = user.followers
  end
  
  private
   def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
   printbinary 
  end
     
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/selects_helper.rb
module SelectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new.html.erb
<h2 class="mt-3">New book</h2>
  <%= form_with model: book, local: true do |f| %>
    <div class="form-group">
      <label for="book_title">Title</label>
      <%= f.text_field :title, class: "form-control book_title" %>
    </div>
    <div class="form-group">
      <label for="book_opinion">Opinion</label>
      <%= f.text_area :body, class: "form-control book_body" %>
    </div>
    <div class="form-group">
      <label for="book_opinion">選択肢A</label>
      <%= f.text_area :select_a, class: "form-control book_body" %>
    </div>
        <div class="form-group">
      <label for="book_opinion">選択肢B</label>
      <%= f.text_area :select_b, class: "form-control book_body" %>
    </div>

    <div class="form-group">
      <%= f.submit "Create Book", class: "btn btn-success" %>
    </div>
  <% end %>

app/views/books/edit.html.erb
<%= form_with model:@book,local:true do |f|%>

<div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <% if @book.errors.any? %>
  <h1><%= @book.errors.count %>errors prohibited this obj from being saved:</h1>
  <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
 <% end %>
 <% end %>

          <h1>Editing Book</h1>
          <%= f.label :title %>
            <div class="form-group">
            <%= f.text_area :title,class:'form-control book_body'%>
            </div>

            <%= f.label :Opinion %>
            <div class="form-group">
            <%= f.text_area :body,class:'form-control book_body' %>
            </div>


            <%= f.submit"Update Book",class:"btn btn-success" %>
            <% end %>

            <div class="edit-footer">
           <%= link_to "Show",book_path(@book)%>
            |
            <%= link_to "Back",books_path %>
            </div>


      </div>
    </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>Errors prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
 <% end %>
 <% end %>
 <p><%= flash[:notice] %></p>
 
   <!--検索窓の作成-->
  <% if user_signed_in? %>
  <%= render 'searchs/search' %>
    <% end %>


<div class="container">  
  <div class="row">      
      <div class="col-md-3"> 
        <%= render 'users/info',user:@user %>
        <%= render 'books/new',book:@book %>
      </div>
       <div class="col-md-8 offset-md-1"> 
          <h2>Books</h2>
          <table class="table table-hover table-inverse">
              <thead> 
               <tr class="border-top border-bottom"> 
                   <th></th>
                   <th>Title</th>
                   <th>Opinion</th>
                   <th colspan="3"></th>
               </tr>
              </thead>
              <% @books.each do |f| %>
              <tbody class="border-top border-bottom">
                  <tr>
                      <td><%= link_to attachment_image_tag(f.user, :profile_image, size: "40x40", format: 'jpg', fallback: "no_image.jpg"),user_path(f.user.id) %></td>
                      <td><%= link_to f.title,book_path(f.id) %></td>
                      <td><%= f.body %></td>
                      <td class="like_buttons_<%= f.id %>">
                        <%= render 'likes/like' ,books:f %>
                        </td>
                  </tr>
              </tbody>
              <%end%>
          </table>
         </div>
  </div>
</div>

app/views/books/show.html.erb
 
<div class="container">  
  <div class="row">
      <div class="col-md-3">     
        <%= render 'users/info',user: @user %>
        <%= render 'books/new',book: @new_book %>
      </div>

       <div class="col-md-8 offset-md-1">
            <h1>Book detail</h1>
          <table class="table">
              <tbody>
                  <tr>
                      <td><p><%= link_to attachment_image_tag(@book.user, :profile_image, size: "60x60" , fallback: "no_image.jpg"),user_path(@user)%><br/>
                      <%= link_to @user.name,user_path(@user) %></p></td>
                      <td><%=link_to @book.title,book_path(@book.id) %></td>
                      <td><%= @book.body %></td>
                      
                      
                      <!--#いいね機能実装部分-->
                      <td class="like_buttons_<%= @book.id %>"><%= render 'likes/like',books:@book %></td>


<% if @book.selects_by?(current_user) %>
<!--# 過去にいいねしたかを確認する。-->
    <td><%= link_to book_selects_path(@book.id),method: :delete do %>
      ♥<%= @book.select_a %></td>
      <% end %>
       <td><%= link_to book_selects_path(@book.id),method: :post do %>
      ♡<%= @book.select_b %></td>
       <% end %>
    
    <% else %>
        <td><%= link_to book_selects_path(@book.id),method: :delete do %>
      ♡<%= @book.select_a %></td>
      <% end %>
       <td><%= link_to book_selects_path(@book.id),method: :post do %>
      ♥<%= @book.select_b %></td>
       <% end %>

 <% end %>







                      
                      <td> <%#= link_to @book.select_a,root_path %> </td>
                      <td> <%#= link_to @book.select_b,root_path %> </td>
    
                      <% if @book.user == current_user %>
                      <td><%= link_to "Edit",edit_book_path(@book),class:'btn btn-sm btn-success' %></td>
                      <td>
                      <%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"}, class:"btn btn-danger" %>
                       </td>
                       
                       <% end %>
                  </tr>
              </tbody>
          </table>
          
   
          <div class ="comment_area">
        <%= render 'comments/comment', book: @book, comment: @comment, comments: @comments %>
        </div>


         </div>
         </div>
  </div>
</div>

app/views/comments/_comment.html.erb
 <!--コメント入力部分-->
        
                                    
          <!--コメント表示部分-->
          <% comments.each do |comments| %>
          <th>
           <td><p><%= link_to attachment_image_tag(comments.user, :profile_image, size: "60x60" , fallback: "no_image.jpg"),user_path(comments.user)%><br/>
            <%= comments.user.name %></p></td>
            <td><%= comments.content %></td>
            <td><%= link_to "削除",book_comment_path(book,comments.id),method: :delete,remote: true %></td>
          </th>
          <% end %>
             <%= form_with(model:[book,comment],remote:true) do |comment| %>
          <th> 
          　<%= comment.text_area :content %>
            <%= comment.submit"決定"%>
            <% end %>
             </th>
          
          
 

app/views/comments/create.js.erb
$(".comment_area").html("<%= j(render 'comments/comment', book: @book, comment: @comment,comments: @comments ) %>");
$(".comment_area").val('');

app/views/comments/destroy.js.erb
$(".comment_area").html("<%= j(render 'comments/comment', book: @book, comment: @comment,comments: @comments ) %>");
$(".comment_area").val('');

app/views/likes/_like.html.erb
<% if books.likes_by?(current_user) %>
<!--# 過去にいいねしたかを確認する。-->
    <%= link_to book_likes_path(books.id),method: :delete,remote: true do %>
      ♥<%= books.likes.count %>いいね</td>
       <% end %>
    
    <% else %>
    
     <%= link_to book_likes_path(books.id),method: :post,remote: true do %>
     ♡<%= books.likes.count %>いいね</td>
         <% end %>

         <%# test %>
         <%# git add  %>
 <% end %>

app/views/likes/create.js.erb
$('.like_buttons_<%= @book.id %>').html("<%= j(render "likes/like", books:@book ) %>");

app/views/likes/destroy.js.erb
$('.like_buttons_<%= @book.id %>').html("<%= j(render "likes/like", books:@book ) %>");

app/views/selects/create.html.erb
<h1>Selects#create</h1>
<p>Find me in app/views/selects/create.html.erb</p>

app/views/users/_info.html.erb
<h2>User info</h2>

<%= attachment_image_tag user, :profile_image, size: "100x100",format: 'jpg', fallback: "no_image.jpg" %>
<table class="table">
    <tbody >
        <tr>
            <th>name</th>
            <th ><%= user.name %></th>
        </tr>
        <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
        </tr>
        <tr>
          <th>フォロー数</th>
          <th><%=link_to user.followings.count,user_followings_path(user.id) %></th>
        </tr>
        
        <tr>
          <th> フォロワー数</th>
          <th><%= link_to user.followers.count,user_followers_path(user.id) %></th>
        </tr>
        
    </tbody>
</table>
 <div class="row">
  <% if user == current_user %>
     <%= link_to "",edit_user_path(current_user),class:"btn btn-outline-secondary btn-block fas fa-user-cog" %>
     <% else %>
     <%= link_to "",edit_user_path(user),class:"btn btn-outline-secondary btn-block fas fa-user-cog" %>
     
     
    <% if user.is_followed_by?(current_user) %>
      
      <%= link_to user_relationships_path(user),method: :delete do %>
      <botton class="btn btn-danger">フォロー解除</botton>
      <% end %>
      
    <% else %>
       
      <%= link_to user_relationships_path(user),method: :post do %>
      <botton class="btn btn-primary">フォロー</botton>
      <% end %>
        
    <% end %>
     
    <% end %> 
 </div>

app/views/users/edit.html.erb
<%= form_with model:@user,local:true do |f| %>

<div class="container">
    <div class="row">
        <div class="col col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
         <h1>User info</h1>
        <% if @user.errors.any? %>
  <h1><%= @user.errors.count %>error prohibited this obj from being saved:</h1>
  <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
 <% end %>
 <% end %>
     
        <%= f.label :name %>
        <div class="form-group">
            <%= f.text_field :name,class:'form-control book_body' %>
        </div>
        
        <%= f.label :Image %>
        <div class="form-group">
        <%= f.attachment_field :profile_image %>
        </div>
        
        <%= f.label :Introduction %>
        <div class="form-group">
        <%= f.text_area :introduction,class:'form-control book_body' %>
        </div>
        
        <%= f.submit"Update User",class:"btn btn-secondary"%>
        </div>
    </div>
</div>
<% end %>

app/views/users/followers.html.erb
<div class="container">  
  <div class="row">
      <div class="col md-7"> 
        <table class="table table-inverse">
       <thead> 
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead> 
    <% @users.each do |users|%>
      <tbody>
        <tr>
          <td><%= attachment_image_tag users, :profile_image, size:'40x40', format: 'jpg', fallback: "no_image.jpg"%></td>
          <td><%= users.name %></td>
          <td>フォロー数<%= users.followings.count %></td>
          <td>フォロワー数<%= users.followers.count %></td>
      </tbody>
      <% end %>
      </table>
      
   </div>
  </div>
</div>

app/views/users/followings.html.erb
<div class="container">  
  <div class="row">
      <div class="col md-7"> 
        <table class="table table-inverse">
       <thead> 
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead> 
    <% @users.each do |users|%>
      <tbody>
        <tr>
          <td><%= attachment_image_tag users, :profile_image, size:'40x40', format: 'jpg', fallback: "no_image.jpg"%></td>
          <td><%= users.name %></td>
          <td>フォロー数<%= users.followings.count %></td>
          <td>フォロワー数<%= users.followers.count %></td>
      </tbody>
      <% end %>
      </table>
      
   </div>
  </div>
</div>

app/views/users/index.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="container">  
  <div class="row">
      <div class="col-md-3">     
        <%= render 'users/info', user:@user %>
        <%= render 'books/new',book:@book %>
      </div>
           <div class="col-md-8 offset-md-1">
          <h2>Users</h2>
           <table class="table table-inverse">
              <thead> 
               <tr> 
                   <th>image</th>
                   <th>name</th>
                   <th colspan="3"></th>
               </tr>
              </thead>
              <% @users.each do |users| %>
              <tbody class="border-top border-bottom">
                  <tr>
                      <td><%= attachment_image_tag users, :profile_image, size:'40x40', format: 'jpg', fallback: "no_image.jpg"%></td>
                      <td><%= users.name %></td>
                      <td>フォロー数<%= users.followings.count %></td>
                      <td>フォロワー数<%= users.followers.count %></td>
                      
                    <% if users != current_user %>
                      <% if users.is_followed_by?(current_user) %>
                        <td><%= link_to user_relationships_path(users),method: :delete do %>
                        <botton class="btn btn-danger">フォロー解除</botton>
                        <% end %>
                      </td>
                      <% else %>
                      <td>
                        <%= link_to user_relationships_path(users),method: :post do %>
                        <botton class="btn btn-primary">フォロー</botton>
                        <% end %>
                      </td>
                      <% end %>
                    <% end %>
                      
                      <td><%= link_to "Show",user_path(users.id)%></td>

                  </tr>
              </tbody>
              <% end %>
          </table>
         
         </div>
  </div>
</div>

app/views/users/show.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>Errors prohibited this obj from being saved:
  <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
 <% end %>
 <% end %>


<div class="container">  
  <div class="row">      
   <div class="col-md-3"> 
     <%= render 'users/info',user:@user %>
     <%= render 'books/new',book:@book %>
   </div>
       <div class="col-md-8 offset-md-1"> 
          <h2>Books</h2>
          <table class="table table-hover table-inverse">
              <thead> 
               <tr class="border-top border-bottom"> 
                   <th></th>
                   <th>Title</th>
                   <th>Opinion</th>
               </tr>
              </thead>
              <% @user_books.each do |user_books| %>
              <tbody class="border-top border-bottom">
                  <tr>
                      <td><%= link_to attachment_image_tag(user_books.user, :profile_image, size: "40x40", format: 'jpg', fallback: "no_image.jpg"),user_path(@user) %> </td>
                      <td><%= link_to user_books.title,book_path(user_books.id) %></td>
                      <td><%= user_books.body %></td>
                      <td></td>
                  </tr>
                  <% end %>
              </tbody>
          </table>
   </div>
  </div>
</div>