config/routes.rb
Rails.application.routes.draw do
  
   get 'home/about' => "homes#about"
  root to:'homes#index'
  
  
  devise_for :users

  resources :homes
  
  resources :users do
    resource :relationships,only:[:create, :destroy]
    # フォローしている人を表示するためのルーティング
    get :followings
    # フォワ−　されている人を表示するためにルーティング
    get :followers
  end
  
    resources :books do 
      resource :likes,only:[:create, :destroy]
      resources :comments,only:[:create,:destroy]
      resource :selects,only:[:create, :destroy]
    end
    
    get '/search' => 'searchs#search'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  

end

app/models/book.rb
class Book < ApplicationRecord
 belongs_to :user 
 has_many :relationships, dependent: :destroy
 has_many :likes, dependent: :destroy
 has_many :comments,dependent: :destroy
 has_many :selects, dependent: :destroy

validates :title, presence: true
validates :body, presence: true, length: { maximum: 200 }


 def likes_by?(user)
  likes.where(user_id: user.id).exists?
 end
 
 def selects_by?(user)
  selects.where(user_id: user.id).exists?
 end
 


end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :book 
  belongs_to :user
  
end

app/models/like.rb
class Like < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
belongs_to :follower, class_name: "User"
belongs_to :following, class_name: "User"

end

app/models/select.rb
class Select < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
 has_many :books,dependent: :destroy
 has_many :likes,dependent: :destroy
 has_many :comments,dependent: :destroy
 has_many :selects, dependent: :destroy
  attachment :profile_image
  
  
  # ----フォロー機能アソシエーション---
  
  #フォローする側のアソシエーション
  has_many :relationships,foreign_key: :following_id
  #フォローする側がフォローしている人の情報取る
  has_many :followings, through: :relationships, source: :follower
  
  
  # フォローされる側のアソシエーション
  has_many :reverse_of_relationships,class_name: 'Relationship',foreign_key: :follower_id
 #フォローされている側がフォローしている情報を取る
  has_many :followers, through: :reverse_of_relationships, source: :following
  

#フォローしているかを確認する
def is_followed_by?(user)
 reverse_of_relationships.find_by(following_id: user.id).present?
end

  validates :name,
    presence: true, uniqueness: true, length: { in: 2..20 }
    # 文字数の制限を設ける→length #長さの範囲を2-20文字→in ..
    # 一意性を保つバリデーション（uniqueness: true）
  validates :introduction,
    length: { maximum: 50 }
    # 長さの下限を50文字に設定→minimum
    # presence: trueは、空欄でないことを確認している


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
#   before_action :current_user, only:[:edit]

def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
        flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book)
    else
    @user = current_user
    @books = Book.all
    render :index
    end 
end

def show
  @new_book = Book.new
  @book = Book.find(params[:id])
  @user = @book.user
  @books = Book.all
  @comment =Comment.new
  @comments = @book.comments
  
end

def index
    @books = Book.all
    @book = Book.new
    @user = current_user
    @users = User.all
end


# ーーー登録ユーザーのみ表示ーーー
  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book)
      flash[:notice] = "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

# ーーー（end)登録ユーザーのみ表示ーーー


private
  def book_params
    params.require(:book).permit(:title,:body,:profile_image)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

app/controllers/likes_controller.rb
class LikesController < ApplicationController

   def create
    @book = Book.find(params[:book_id])
    favorite = current_user.likes.new(book_id: @book.id)
    favorite.save
 
   end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = Like.find_by(user_id: current_user.id, book_id: @book.id)
    favorite.destroy
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!
  before_action :current_user, only:[:edit,:update]
    
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
    @not_current_user = User.where.not(id: @user.id)
  end
    
  def show
    @user = User.find(params[:id])
    @user_books = @user.books
    @book = Book.new
    @books = Book.all
  end
    
  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end
    
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path
    else
      render :edit
    end 
  end
  
  
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end
  
  def followers
     user = User.find(params[:user_id])
     @users = user.followers
  end
  
  private
   def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
   printbinary 
  end
     
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/selects_helper.rb
module SelectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
        <nav class="navbar navbar-expand-lg text-white navbar-dark bg-dark">
          <div class="container">
              <%= link_to "Bookers",root_path,class:"navbar-brand" %>
                <div class="collapse navbar-collapse">
                  <ul class="navbar-nav ml-auto">
                    
                    <% if user_signed_in? %>
                    <li><%= link_to "Home",user_path(current_user.id),class:"fas fa-home nav-link text-light" %></li>
                    <li><%= link_to "Users",users_path,class:"fas fa-users nav-link text-light" %></li>
                    <li><%= link_to "Books",books_path,class:"fas fa-book-open nav-link text-light" %></li>
                    <li><%= link_to "logout",destroy_user_session_path,method: :delete,class:"fas fa-sign-out-alt nav-link text-light" %></li>
                    <% else %>
                    <li><%= link_to "Home",root_path,class:"fas fa-home nav-link text-light" %></li>
                    <li><%= link_to "About",home_about_path,class:"fas fa-link nav-link text-light" %></li>
                    <li><%= link_to "sign up",new_user_registration_path, class:"fas fa-user-plus nav-link text-light" %></li>
                    <li><%= link_to "login",new_user_session_path, class:"fas fa-sign-in-alt nav-link text-light" %></li>
                    <% end %>
                  </ul>
                </div>
            </div>
      </nav>
    </header>
 <% flash.each do |message_type, message| %>
    <%= content_tag :div, message, class: message_type %>
    <% end %>
    

    <%= yield %>
    
    
    <footer>
  <div class="container">
    <div class="row">
      <div class="mx-auto">
        CopyRight Infratop.inc
      </div>
    </div>
  </div>
</footer>
  </body>
</html>